 INSERT INTO ACCOUNT("ACCOUNT_NUMBER","ACCOUNT_TYPE")VALUES('235654','saving');
  INSERT INTO ACCOUNT("ACCOUNT_NUMBER","ACCOUNT_TYPE")VALUES('235653','saving');
  
  INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');

INSERT INTO "USERS"("PASSWORD","USERNAME")VALUES('$2a$10$Ffg.I3oC34znTT6I1S1g/OXIdNFpjczSQbHC4FgtYJb66K2P5Uxam','testAdmin');
INSERT INTO "USERS"("PASSWORD","USERNAME")VALUES('$2a$10$/0IW8ONsKGOZD7NLg6xyteVnwT8icOST68B2hcG5qQeGzQ2dhbyPO','testUser');
INSERT INTO "USER_ROLES"("USER_ID","ROLE_ID")VALUES(1,3);
INSERT INTO "USER_ROLES"("USER_ID","ROLE_ID")VALUES(2,1); 	  
INSERT INTO "STATEMENT"("ACCOUNT_ID","AMOUNT","DATEFIELD")VALUES(1,'1300','2020-03-01'); 
INSERT INTO "STATEMENT"("ACCOUNT_ID","AMOUNT","DATEFIELD")VALUES(1,'1600','2020-02-01'); 
INSERT INTO "STATEMENT"("ACCOUNT_ID","AMOUNT","DATEFIELD")VALUES(1,'1900','2020-05-01'); 
INSERT INTO "STATEMENT"("ACCOUNT_ID","AMOUNT","DATEFIELD")VALUES(1,'2300','2020-09-01'); 
INSERT INTO "STATEMENT"("ACCOUNT_ID","AMOUNT","DATEFIELD")VALUES(1,'4600','2020-10-01'); 
INSERT INTO "STATEMENT"("ACCOUNT_ID","AMOUNT","DATEFIELD")VALUES(1,'5900','2020-12-01'); 
      
